# Generated by Django 5.1 on 2024-10-01 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0002_alter_post_author_alter_post_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="active",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
