# Generated by Django 5.1 on 2024-10-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0004_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
